EJS.Helpers.prototype.date_tag=function(b,c){c instanceof Date||(c=new Date);for(var a="January,February,March,April,May,June,July,August,September,October,November,December".split(","),d=[],e=[],f=[],h=c.getFullYear(),i=c.getMonth(),j=c.getDate(),g=h-15;g<h+15;g++)d.push({value:g,text:g});for(g=0;12>g;g++)e.push({value:g,text:a[g]});for(a=0;31>a;a++)f.push({value:a+1,text:a+1});d=this.select_tag(b+"[year]",h,d,{id:b+"[year]"});e=this.select_tag(b+"[month]",i,e,{id:b+"[month]"});f=this.select_tag(b+
"[day]",j,f,{id:b+"[day]"});return d+e+f};EJS.Helpers.prototype.form_tag=function(b,c){c=c||{};c.action=b;if(!0==c.multipart)c.method="post",c.enctype="multipart/form-data";return this.start_tag_for("form",c)};EJS.Helpers.prototype.form_tag_end=function(){return this.tag_end("form")};EJS.Helpers.prototype.hidden_field_tag=function(b,c,a){return this.input_field_tag(b,c,"hidden",a)};
EJS.Helpers.prototype.input_field_tag=function(b,c,a,d){d=d||{};d.id=d.id||b;d.value=c||"";d.type=a||"text";d.name=b;return this.single_tag_for("input",d)};EJS.Helpers.prototype.is_current_page=function(b){return window.location.href==b||window.location.pathname==b?!0:!1};
EJS.Helpers.prototype.link_to=function(b,c,a){b||(b="null");a||(a={});if(a.confirm)a.onclick=' var ret_confirm = confirm("'+a.confirm+'"); if(!ret_confirm){ return false;} ',a.confirm=null;a.href=c;return this.start_tag_for("a",a)+b+this.tag_end("a")};
EJS.Helpers.prototype.submit_link_to=function(b,c,a){b||(b="null");a||(a={});a.onclick=a.onclick||"";if(a.confirm)a.onclick=' var ret_confirm = confirm("'+a.confirm+'"); if(!ret_confirm){ return false;} ',a.confirm=null;a.value=b;a.type="submit";a.onclick=a.onclick+(c?this.url_for(c):"")+"return false;";return this.start_tag_for("input",a)};EJS.Helpers.prototype.link_to_if=function(b,c,a,d,e,f){return this.link_to_unless(!1==b,c,a,d,e,f)};
EJS.Helpers.prototype.link_to_unless=function(b,c,a,d,e){d=d||{};return b?e&&"function"==typeof e?e(c,a,d,e):c:this.link_to(c,a,d)};EJS.Helpers.prototype.link_to_unless_current=function(b,c,a,d){a=a||{};return this.link_to_unless(this.is_current_page(c),b,c,a,d)};EJS.Helpers.prototype.password_field_tag=function(b,c,a){return this.input_field_tag(b,c,"password",a)};
EJS.Helpers.prototype.select_tag=function(b,c,a,d){d=d||{};d.id=d.id||b;d.value=c;d.name=b;b=""+this.start_tag_for("select",d);for(d=0;d<a.length;d++){var e=a[d],f={value:e.value};if(e.value==c)f.selected="selected";b+=this.start_tag_for("option",f)+e.text+this.tag_end("option")}return b+=this.tag_end("select")};EJS.Helpers.prototype.single_tag_for=function(b,c){return this.tag(b,c,"/>")};EJS.Helpers.prototype.start_tag_for=function(b,c){return this.tag(b,c)};
EJS.Helpers.prototype.submit_tag=function(b,c){c=c||{};c.type=c.type||"submit";c.value=b||"Submit";return this.single_tag_for("input",c)};EJS.Helpers.prototype.tag=function(b,c,a){a||(a=">");var d=" ",e;for(e in c){var f=null!=c[e]?c[e].toString():"";"Class"==e&&(e="class");d=-1!=f.indexOf("'")?d+(e+'="'+f+'" '):d+(e+"='"+f+"' ")}return"<"+b+d+a};EJS.Helpers.prototype.tag_end=function(b){return"</"+b+">"};
EJS.Helpers.prototype.text_area_tag=function(b,c,a){a=a||{};a.id=a.id||b;a.name=a.name||b;c=c||"";if(a.size)a.cols=a.size.split("x")[0],a.rows=a.size.split("x")[1],delete a.size;a.cols=a.cols||50;a.rows=a.rows||4;return this.start_tag_for("textarea",a)+c+this.tag_end("textarea")};EJS.Helpers.prototype.text_tag=EJS.Helpers.prototype.text_area_tag;EJS.Helpers.prototype.text_field_tag=function(b,c,a){return this.input_field_tag(b,c,"text",a)};
EJS.Helpers.prototype.url_for=function(b){return'window.location="'+b+'";'};EJS.Helpers.prototype.img_tag=function(b,c,a){a=a||{};a.src=b;a.alt=c;return this.single_tag_for("img",a)};
